# Generated by Django 4.2.9 on 2024-02-01 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('project', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('time', models.FloatField(choices=[(0.25, '15 mins'), (0.5, '30 mins'), (0.75, '45 mins'), (1.0, '1h mins'), (1.25, '1h 15 mins'), (1.5, '1h 30 mins'), (1.75, '1h 45 mins'), (2.0, '2h'), (2.25, '2h 15 mins'), (2.5, '2h 30 mins'), (2.75, '2h 45 mins'), (3.0, '3h'), (3.25, '3h 15 mins'), (3.5, '3h 30 mins'), (3.75, '3h 45 mins'), (4.0, '4h'), (4.25, '4h 15 mins'), (4.5, '4h 30 mins'), (4.75, '4h 45 mins'), (5.0, '5h'), (6.25, '6h 15 mins'), (6.5, '6h 30 mins'), (6.75, '6h 45 mins'), (7.0, '7h'), (7.25, '7h 15 mins'), (7.5, '7h 30 mins'), (7.75, '7h 45 mins'), (8.0, '8h'), (8.25, '8h 15 mins'), (8.5, '8h 30 mins'), (8.75, '8h 45 mins'), (9.0, '9h'), (9.25, '9h 15 mins'), (9.5, '9h 30 mins'), (9.75, '9h 45 mins'), (10.0, '10h'), (10.25, '10h 15 mins'), (10.5, '10h 30 mins'), (10.75, '10h 45 mins'), (11.0, '11h'), (11.25, '11h 15 mins'), (11.5, '11h 30 mins'), (11.75, '11h 45 mins'), (12.0, '12h')])),
                ('date', models.CharField(default=datetime.date(2024, 2, 1), max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timely.employees')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pname', to='timely.clients')),
            ],
        ),
    ]
