# Generated by Django 4.2.9 on 2024-02-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name_plural': 'Hours'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='project',
        ),
        migrations.AlterField(
            model_name='hours',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timely.clients')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterField(
            model_name='hours',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timely.projects'),
        ),
    ]
