# Generated by Django 4.2.9 on 2024-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0005_alter_hours_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
