# Generated by Django 4.2.9 on 2024-02-02 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0007_alter_hours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 13, 38, 39, 807361, tzinfo=datetime.timezone.utc)),
        ),
    ]
