# Generated by Django 4.2.9 on 2024-02-02 13:42

import datetime
from django.db import migrations, models
import timely.models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0008_alter_hours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[timely.models.Hours.Date_validation]),
        ),
    ]
