# Generated by Django 4.2.9 on 2024-02-06 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0014_alter_vacation_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='start',
            field=models.DateField(default=datetime.datetime(2024, 2, 6, 12, 41, 27, 942273, tzinfo=datetime.timezone.utc)),
        ),
    ]
