# Generated by Django 4.2.9 on 2024-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0015_alter_vacation_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='start',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
