# Generated by Django 4.2.9 on 2024-02-08 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0018_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
