# Generated by Django 4.2.9 on 2024-02-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0019_hours_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTime'),
        ),
    ]
