# Generated by Django 4.2.9 on 2024-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0020_alter_hours_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
