# Generated by Django 4.2.9 on 2024-02-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0022_vacation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='days',
        ),
    ]
