# Generated by Django 4.2.9 on 2024-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0023_remove_vacation_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='approval_status',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='employees',
            name='fullname',
            field=models.CharField(default='This gets autofilled, do not touch it please', max_length=200),
        ),
    ]
