# Generated by Django 4.2.9 on 2024-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0025_vacation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='approved',
        ),
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='days',
            field=models.IntegerField(blank=True, verbose_name='Vacation Days, gets autocalculated'),
        ),
    ]
