# Generated by Django 4.2.9 on 2024-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0027_alter_vacation_days_alter_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='days',
            field=models.IntegerField(blank=True, verbose_name='Vacation Days (do not touch, gets auto-calculated)'),
        ),
    ]
