# Generated by Django 4.2.9 on 2024-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0028_alter_vacation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='office',
            field=models.CharField(choices=[('GERMANY', 'Germany'), ('GR 1', 'GR Office 1'), ('GR 2', 'GR Office 2')], default='GERMANY', max_length=10),
        ),
    ]
