# Generated by Django 4.2.9 on 2024-02-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timely', '0029_employees_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='fullname',
            field=models.CharField(blank=True, default='This gets autofilled, do not touch it please', max_length=200),
        ),
    ]
